#!/bin/bash

echo "🚀 CRIANDO USUÁRIOS NO RAILWAY"
echo "=============================="
echo ""

cd "/Users/andremontenegro/agendamento claude code/fitness-scheduler"

echo "📝 INSTRUÇÕES SIMPLES:"
echo ""
echo "1️⃣ PRIMEIRO, execute este comando:"
echo ""
echo -e "\033[1;32m"
echo "railway shell"
echo -e "\033[0m"
echo ""
echo "2️⃣ QUANDO ABRIR O SHELL, execute:"
echo ""
echo -e "\033[1;32m"
echo "node create-users-direct.js"
echo -e "\033[0m"
echo ""
echo "3️⃣ DEPOIS, saia do shell:"
echo ""
echo -e "\033[1;32m"
echo "exit"
echo -e "\033[0m"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "COMANDO COMPLETO PARA COPIAR E COLAR:"
echo ""
echo -e "\033[1;33m"
echo "railway shell && node create-users-direct.js && exit"
echo -e "\033[0m"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Depois disso, as credenciais funcionarão:"
echo "   • trainer@test.com / 123456"
echo "   • client@test.com / 123456"
echo ""
echo "🌐 Site: https://fitness-scheduler-production.up.railway.app"
echo ""