#!/bin/bash

echo "🚀 RESOLVENDO O PROBLEMA DO RAILWAY DEFINITIVAMENTE"
echo "==================================================="
echo ""

cd "/Users/andremontenegro/agendamento claude code/fitness-scheduler"

echo "📋 INSTRUÇÕES PASSO A PASSO:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣ PRIMEIRO - No Railway Dashboard:"
echo ""
echo "   a) Acesse: https://railway.app/dashboard"
echo "   b) No projeto fitness-scheduler"
echo "   c) DELETE o serviço Postgres atual (3 pontinhos → Remove)"
echo "   d) Clique em '+ New' → 'Database' → 'Add PostgreSQL'"
echo "   e) Aguarde 1 minuto para criar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣ SEGUNDO - Copie a URL do novo banco:"
echo ""
echo "   a) Clique no novo Postgres"
echo "   b) Vá na aba 'Connect'"
echo "   c) Copie 'Postgres Connection URL'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3️⃣ TERCEIRO - Configure no fitness-scheduler:"
echo ""
echo "   a) Vá no serviço fitness-scheduler"
echo "   b) Clique em 'Variables'"
echo "   c) Edite DATABASE_URL"
echo "   d) Cole a nova URL"
echo "   e) Salve"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4️⃣ QUARTO - Aguarde 3 minutos e execute:"
echo ""
echo -e "\033[1;32m"
echo "railway shell"
echo "node create-users-direct.js"
echo "exit"
echo -e "\033[0m"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ PRONTO! As credenciais funcionarão:"
echo "   • trainer@test.com / 123456"
echo "   • client@test.com / 123456"
echo ""
echo "🌐 Site: https://fitness-scheduler-production.up.railway.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 DICA: Se preferir, crie um banco gratuito em:"
echo "   https://neon.tech/ (recomendado)"
echo "   https://supabase.com/"
echo "   https://elephantsql.com/"
echo ""