#!/bin/bash

echo "🔧 Fixing Production Users on Railway"
echo "====================================="
echo ""

cd "/Users/andremontenegro/agendamento claude code/fitness-scheduler"

echo "📊 This script will help fix the test users in production."
echo ""

echo "Option 1: Run diagnosis and fix automatically"
echo "=============================================="
echo "Execute these commands:"
echo ""
echo -e "\033[0;32m"
echo "railway run npm run diagnose"
echo -e "\033[0m"
echo ""
echo "This will:"
echo "- Check database connection"
echo "- List all existing users"
echo "- Create or fix test users"
echo "- Ensure passwords are correct"
echo ""

echo "Option 2: Force recreate test users"
echo "===================================="
echo "Execute these commands:"
echo ""
echo -e "\033[0;32m"
echo "railway run npx prisma db push --force-reset"
echo "railway run npm run seed-production"
echo -e "\033[0m"
echo ""
echo "⚠️  WARNING: Option 2 will DELETE ALL DATA!"
echo ""

echo "Option 3: Manual check via Railway shell"
echo "========================================"
echo "Execute:"
echo ""
echo -e "\033[0;32m"
echo "railway shell"
echo "npx prisma studio"
echo -e "\033[0m"
echo ""
echo "Then open the URL provided to see your database"
echo ""

echo "Option 4: Create users via API"
echo "==============================="
echo "You can also register new users directly on the website:"
echo "https://fitness-scheduler-production.up.railway.app/register"
echo ""

echo "Expected credentials after fix:"
echo "==============================="
echo "Trainer: trainer@test.com / 123456"
echo "Client: client@test.com / 123456"
echo ""

echo "To verify if fix worked:"
echo "========================"
echo "railway run npm run check-users"
echo ""