#!/bin/bash

echo "🔧 Fixing DATABASE_URL in Railway"
echo "================================="
echo ""

cd "/Users/andremontenegro/agendamento claude code/fitness-scheduler"

echo "📊 Current Railway Variables:"
railway variables | grep -E "(DATABASE|POSTGRES)" || echo "No database variables found"

echo ""
echo "🔍 Looking for Postgres service..."
echo ""

echo "⚠️  IMPORTANT: You need to manually set DATABASE_URL"
echo ""
echo "Option 1 - Via Railway Dashboard (RECOMMENDED):"
echo "================================================"
echo "1. Go to: https://railway.app/dashboard"
echo "2. Click on 'fitness-scheduler' project"
echo "3. You should see TWO services:"
echo "   - fitness-scheduler (your app)"
echo "   - Postgres (database)"
echo ""
echo "4. Click on the 'fitness-scheduler' service"
echo "5. Go to 'Variables' tab"
echo "6. Look for DATABASE_URL"
echo "7. If it exists, DELETE it first"
echo "8. Click 'New Variable'"
echo "9. Name: DATABASE_URL"
echo "10. Click the REFERENCE button (looks like <>)"
echo "11. Select: Postgres → DATABASE_URL"
echo "12. Save"
echo ""

echo "Option 2 - Get URL from Postgres service:"
echo "=========================================="
echo "1. In Railway Dashboard, click on 'Postgres' service"
echo "2. Go to 'Connect' tab"
echo "3. Copy the 'Postgres Connection URL'"
echo "4. Go back to 'fitness-scheduler' service"
echo "5. Add variable: DATABASE_URL = [paste the URL]"
echo ""

echo "After fixing DATABASE_URL:"
echo "=========================="
echo "The Railway will automatically redeploy"
echo "Check logs with: railway logs"
echo ""

echo "Expected DATABASE_URL format:"
echo "postgresql://postgres:PASSWORD@postgres.railway.internal:5432/railway"
echo ""