services:
  - type: web
    name: fitness-scheduler
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        value: fitness-scheduler-jwt-super-secure-secret-key-production-32-chars
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: PORT
        value: 3000