#!/bin/bash

echo "🧪 TESTE MANUAL RÁPIDO DO SISTEMA"
echo "================================="
echo ""
echo "📱 Abra o navegador em: http://localhost:3001"
echo ""
echo "✅ CHECKLIST DE TESTES MANUAIS:"
echo ""
echo "1️⃣ TESTE COMO CLIENT (client@test.com / 123456)"
echo "   □ Login funciona?"
echo "   □ Dashboard carrega?"
echo "   □ Link 'Agendar Treino' funciona?"
echo "   □ Consegue ver treinadores disponíveis?"
echo "   □ Consegue selecionar data/hora?"
echo "   □ Consegue confirmar agendamento?"
echo "   □ Agendamento aparece em 'Meus Agendamentos'?"
echo "   □ Consegue cancelar agendamento?"
echo "   □ Notificações aparecem?"
echo "   □ Logout funciona?"
echo ""
echo "2️⃣ TESTE COMO TRAINER (trainer@test.com / 123456)"
echo "   □ Login funciona?"
echo "   □ Dashboard carrega?"
echo "   □ Consegue ver agenda/calendário?"
echo "   □ Agendamentos dos clientes aparecem?"
echo "   □ Consegue configurar disponibilidade?"
echo "   □ Consegue adicionar/editar serviços?"
echo "   □ Consegue ver lista de clientes?"
echo "   □ Analytics/Relatórios funcionam?"
echo "   □ Notificações aparecem?"
echo "   □ Logout funciona?"
echo ""
echo "3️⃣ TESTE DE REGISTRO"
echo "   □ Página de registro abre?"
echo "   □ Consegue escolher tipo (Client/Trainer)?"
echo "   □ Formulário valida campos?"
echo "   □ Registro cria conta nova?"
echo "   □ Consegue fazer login com nova conta?"
echo ""
echo "4️⃣ TESTE DE RESPONSIVIDADE"
echo "   □ Site funciona no celular?"
echo "   □ Menu mobile aparece?"
echo "   □ Botões são clicáveis no mobile?"
echo "   □ Formulários funcionam no mobile?"
echo ""
echo "📝 ANOTE OS PROBLEMAS ENCONTRADOS:"
echo "___________________________________"
echo ""
echo ""
echo ""
echo "🔗 Links Diretos para Teste:"
echo "   Login: http://localhost:3001/login"
echo "   Registro: http://localhost:3001/register"
echo "   Dashboard Client: http://localhost:3001/dashboard/client"
echo "   Dashboard Trainer: http://localhost:3001/dashboard/trainer"
echo "   Agendar: http://localhost:3001/schedule"
echo "   Agendamentos: http://localhost:3001/appointments"
echo ""
echo "🚀 Servidor rodando em: http://localhost:3001"